# Generated by Django 4.2.1 on 2023-07-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmation',
            old_name='expiration_tme',
            new_name='expiration_time',
        ),
    ]
