# Generated by Django 4.2.1 on 2024-02-19 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userconfirmation_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 22, 2, 37, 754165)),
        ),
    ]
