# Generated by Django 4.2.1 on 2024-02-26 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userconfirmation_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 8, 11, 36, 300788, tzinfo=datetime.timezone.utc)),
        ),
    ]
