# Generated by Django 4.2.1 on 2023-07-31 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_expiration_tme_userconfirmation_expiration_time'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
